SELECT TOP (1000) [Year]
      ,[SalesOrderID]
      ,[ProductID]
      ,[Name]
      ,[OrderDate]
      ,[DueDate]
      ,[ShipDate]
      ,[SalesOrderNumber]
      ,[PurchaseOrderNumber]
      ,[AccountNumber]
      ,[CustomerID]
      ,[CompanyName]
      ,[ShipToAddressID]
      ,[BillToAddressID]
      ,[CountryRegion]
      ,[CreditCardApprovalCode]
      ,[OrderQty]
      ,[UnitPrice]
      ,[UnitPriceDiscount]
      ,[Cost]
      ,[LineTotal]
      ,[SubTotal]
      ,[TaxAmt]
      ,[Freight]
      ,[TotalDue]
  FROM [AdventureWorksLT2012].[dbo].[customer_analysis]
